FROM openjdk
WORKDIR usr/lib
ADD ./target/userauthenticationservice1-0.0.1-SNAPSHOT.jar /usr/lib/userauthenticationservice1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","userauthenticationservice1-0.0.1-SNAPSHOT.jar"]