version: '3.9'
services:
  music-service:
    image: trackimage
    container_name: trackcontainer
    build: MusicService
    restart: always
    networks:
      - mynetwork
    ports:
      - 8086:8086
    depends_on:
      - mongoService

  mongoService:
    image: mongo
    container_name: mongocontainer
    ports:
      - 27017:27017
    networks:
      - mynetwork
  authentication-service:
    image: authenticationimg
    container_name: authcontainer
    build: UserAuthentication
    restart: always
    networks:
      - mynetwork
    ports:
      - 8085:8085
    depends_on:
      - mysqlService

  mysqlService:
    image: mysql
    container_name: mysqlContainer
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

networks:
  mynetwork:
    driver: bridge